apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: mm
  namespace: mm
spec:
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationProduction
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
  logFormat: basic
  barURL: 'http://upmc-nexusrepo-sonatype-nexus-service.nexus.svc.cluster.local:8081/repository/ibm-ace-bar-files/mm.bar'
  configurations:
    - nexus-auth
  version: '12.0'
  replicas: 1
